services:
  frames:
    image: elevenam/frames:latest
    #ports:
    #  - "3000:3000"
    #volumes:
    #  - /path/to/your/media:/media
    environment:
      - DATABASE_URL=postgres://frames:frames_password@postgres:5432/frames
      - DIRECT_DATABASE_URL=postgres://frames:frames_password@postgres:5432/frames
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=86400
      - REDIS_DB=0
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frames.rule=Host(`frames.iab.lu`)"
      - "traefik.http.routers.frames.entrypoints=websecure"
      - "traefik.http.routers.frames.tls.certresolver=mydnschallenge"
      - "traefik.http.services.frames.loadbalancer.server.port=3000"
      #- "traefik.http.routers.ejbca.middlewares=traefik-forward-auth"
      - "traefik.docker.network=traefik"
    networks:
      - frames-internal
      - traefik

  postgres:
    image: pgvector/pgvector:pg14
    environment:
      - POSTGRES_USER=frames
      - POSTGRES_PASSWORD=frames_password
      - POSTGRES_DB=frames
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frames-internal

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - frames-internal

volumes:
  postgres_data:
  redis_data:
  
networks:
  frames-internal:
  traefik:
    external: true
