services:
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      - guacamole-internal
    restart: always
    #volumes:
    #- ./drive:/drive:rw
    #- ./record:/record:rw

  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      - guacamole-internal
    restart: always
    volumes:
    - /opt/conf/guacamole/postgres/init:/docker-entrypoint-initdb.d
    - /opt/conf/guacamole/postgres/data:/var/lib/postgresql/data

  guacamole:
    container_name: guacamole_compose
    group_add:
      - "1000"
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      #RECORDING_SEARCH_PATH: /record
    image: guacamole/guacamole
    networks:
      - guacamole-internal
      - traefik
    #volumes:
    #  - ./record:/record:rw
    #ports:
    #  - 8080:8080/tcp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.iab.lu`)"
      - "traefik.http.routers.guacamole.entrypoints=websecure"
      - "traefik.http.routers.guacamole.tls.certresolver=mydnschallenge"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      #- "traefik.http.routers.metube.middlewares=traefik-forward-auth"
      - "traefik.docker.network=traefik"
    
networks:
  guacamole-internal:
  traefik:
    external: true
